# Generated by Django 6.0.3 on 2026-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_bot', models.BooleanField(default=False)),
                ('intent', models.CharField(blank=True, choices=[('greeting', 'Greeting'), ('election', 'Election Info'), ('candidate', 'Candidate Info'), ('vote', 'Voting Process'), ('result', 'Election Results'), ('turnout', 'Live Turnout'), ('help', 'Help'), ('other', 'Other')], help_text='Detected intent of the user message', max_length=20)),
                ('feedback', models.BooleanField(blank=True, help_text='User feedback: True=helpful, False=not helpful', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
