# Generated by Django 6.0.3 on 2026-04-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_winner',
            field=models.BooleanField(default=False, help_text='Was this candidate elected?'),
        ),
    ]
