# Generated by Django 6.0.3 on 2026-04-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Text Answer'), ('boolean', 'Yes/No'), ('file', 'File Upload')], default='text', max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='fee_statement',
            field=models.FileField(blank=True, help_text='Official fee statement (PDF)', null=True, upload_to='fee_statements/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='has_cleared_fees',
            field=models.BooleanField(default=False, help_text='Admin: has cleared all fees?'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_nomination_certificate',
            field=models.FileField(blank=True, help_text='Signed party nomination letter', null=True, upload_to='certs/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='questionnaire_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
    ]
