# Generated by Django 6.0.3 on 2026-04-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_candidatequestion_candidate_fee_statement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatequestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores additional info like gender, hall, school, etc.'),
        ),
    ]
