# Generated by Django 6.0.3 on 2026-04-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_candidatequestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='slogan',
            field=models.CharField(blank=True, help_text='Party slogan or motto', max_length=200),
        ),
        migrations.AddField(
            model_name='party',
            name='term',
            field=models.CharField(blank=True, help_text='e.g., One Term, Two Terms', max_length=50),
        ),
    ]
