# Generated by Django 6.0.3 on 2026-04-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_party_slogan_party_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='eligibility_pending',
            field=models.BooleanField(default=False, help_text='Manual eligibility verification required?'),
        ),
    ]
