# Generated by Django 4.2.30 on 2026-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_candidate_eligibility_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='voter_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
    ]
