# Generated by Django 4.2.30 on 2026-05-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_user_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='voter_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
