# Generated by Django 6.0.3 on 2026-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attack_type', models.CharField(choices=[('bruteforce', 'Brute Force'), ('sqli', 'SQL Injection'), ('xss', 'Cross‑Site Scripting'), ('idor', 'Insecure Direct Object Reference'), ('dos', 'Denial of Service'), ('unknown', 'Unknown')], max_length=20)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, help_text='Username if authenticated', max_length=150)),
                ('user_id', models.IntegerField(blank=True, help_text='User ID if authenticated', null=True)),
                ('request_path', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=10)),
                ('request_data', models.TextField(blank=True, help_text='Relevant request data (sanitized)')),
                ('description', models.TextField(blank=True)),
                ('blocked', models.BooleanField(default=False, help_text='Was the request blocked?')),
                ('resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='security_at_ip_addr_923054_idx'), models.Index(fields=['attack_type', 'severity'], name='security_at_attack__456965_idx')],
            },
        ),
    ]
