# Generated by Django 6.0.3 on 2026-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ip_concentration', 'IP Concentration'), ('rapid_votes', 'Rapid Votes'), ('geo_outlier', 'Geographic Outlier')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.FloatField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestoSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.FloatField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
