# Generated by Django 6.0.3 on 2026-03-31 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyalert',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election'),
        ),
        migrations.AddField(
            model_name='feedbacksentiment',
            name='feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='voting.feedback'),
        ),
        migrations.AddField(
            model_name='manifestosentiment',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifesto_sentiment', to='voting.candidate'),
        ),
    ]
